[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!

members = [
    "cerebral-rs",
    "cerebral",
    "potpourri-rs",
    "potpourri"
]

[build]
rustdocflags = ["--html-in-header", "./src/docs-header.html"]
